apiVersion: v1
kind: Namespace
metadata:
  name: example-namespace
---
apiVersion: habitat.sh/v1beta2
kind: Habitat
metadata:
  name: example-namespaced-habitat
  namespace: example-namespace
spec:
  # the core/redis habitat service packaged as a Docker image
  image: habitat/redis-hab
  count: 1
  service:
    name: redis
    topology: standalone
    # if not present, defaults to "default"
    group: foobar
