apiVersion: v1
kind: Secret
metadata:
  name: user-toml
type: Opaque
data:
  # Each item needs to be base64-encoded.
  # This overrides the port set in the Redis Habitat service.
  # Plain text content of the secret: "port = 4444"
  user.toml: cG9ydCA9IDQ0NDQ=
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-bind-configured-db
customVersion: v1beta2
spec:
  image: habitat/redis-hab
  count: 1
  service:
    name: redis
    # Name of the secret.
    # This is mounted inside of the pod as a user.toml file.
    configSecretName: user-toml
    topology: standalone
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-bind-configured-web-app
customVersion: v1beta2
spec:
  image: habitat/bindgo-hab
  count: 1
  service:
    name: hab-server-go
    topology: standalone
    bind:
      - name: db
        service: redis
        group: default
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  selector:
    habitat-name: example-bind-configured-web-app
  type: NodePort
  ports:
  - name: web
    nodePort: 30001
    port: 5555
    protocol: TCP
