apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-leader-follower-habitat
customVersion: v1beta2
spec:
  v1beta2:
    # the core/redis habitat service packaged as a Docker image
    image: habitat/redis-hab
    # count must be at least 3 for a leader-follower topology
    count: 3
    service:
      name: consul
      topology: leader
      # if not present, defaults to "default"
      group: foobar
