// Copyright (c) 2018 Chef Software Inc. and/or applicable contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was automatically generated, DO NOT EDIT.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/habitat-sh/habitat-operator/pkg/apis/habitat/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HabitatLister helps list Habitats.
type HabitatLister interface {
	// List lists all Habitats in the indexer.
	List(selector labels.Selector) (ret []*v1beta1.Habitat, err error)
	// Habitats returns an object that can list and get Habitats.
	Habitats(namespace string) HabitatNamespaceLister
	HabitatListerExpansion
}

// habitatLister implements the HabitatLister interface.
type habitatLister struct {
	indexer cache.Indexer
}

// NewHabitatLister returns a new HabitatLister.
func NewHabitatLister(indexer cache.Indexer) HabitatLister {
	return &habitatLister{indexer: indexer}
}

// List lists all Habitats in the indexer.
func (s *habitatLister) List(selector labels.Selector) (ret []*v1beta1.Habitat, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Habitat))
	})
	return ret, err
}

// Habitats returns an object that can list and get Habitats.
func (s *habitatLister) Habitats(namespace string) HabitatNamespaceLister {
	return habitatNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// HabitatNamespaceLister helps list and get Habitats.
type HabitatNamespaceLister interface {
	// List lists all Habitats in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1beta1.Habitat, err error)
	// Get retrieves the Habitat from the indexer for a given namespace and name.
	Get(name string) (*v1beta1.Habitat, error)
	HabitatNamespaceListerExpansion
}

// habitatNamespaceLister implements the HabitatNamespaceLister
// interface.
type habitatNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Habitats in the indexer for a given namespace.
func (s habitatNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.Habitat, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Habitat))
	})
	return ret, err
}

// Get retrieves the Habitat from the indexer for a given namespace and name.
func (s habitatNamespaceLister) Get(name string) (*v1beta1.Habitat, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("habitat"), name)
	}
	return obj.(*v1beta1.Habitat), nil
}
