apiVersion: v1
kind: Secret
metadata:
  # the name must mirror the ring filename, without the extension
  name: example-encrypted-ring-20170829113029
  labels:
    habitat: "true"
    ring-key: "true"
type: Opaque
data:
  # base64-encoded ring key
  ring-key: U1lNLVNFQy0xCmV4YW1wbGUtZW5jcnlwdGVkLXJpbmctMjAxNzA4MjkxMTMwMjkKClFGZm9ZTHJOV3NNRk93Tk4wb0F1d3d4WjA1aVBMdTQxSUdGSzJISVFqTlk9
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-encrypted-habitat
spec:
  # the core/redis habitat service packaged as a Docker image
  image: habitat/redis-hab
  count: 3
  service:
    name: redis
    topology: leader
    # the name of the secret containing the ring key
    ringSecretName: example-encrypted-ring-20170829113029
