// Copyright (c) 2018 Chef Software Inc. and/or applicable contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was automatically generated, DO NOT EDIT.

// This file was automatically generated by informer-gen

package v1beta1

import (
	habitat_v1beta1 "github.com/habitat-sh/habitat-operator/pkg/apis/habitat/v1beta1"
	versioned "github.com/habitat-sh/habitat-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/habitat-sh/habitat-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/habitat-sh/habitat-operator/pkg/client/listers/habitat/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// HabitatInformer provides access to a shared informer and lister for
// Habitats.
type HabitatInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.HabitatLister
}

type habitatInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHabitatInformer constructs a new informer for Habitat type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHabitatInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHabitatInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHabitatInformer constructs a new informer for Habitat type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHabitatInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HabitatV1beta1().Habitats(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HabitatV1beta1().Habitats(namespace).Watch(options)
			},
		},
		&habitat_v1beta1.Habitat{},
		resyncPeriod,
		indexers,
	)
}

func (f *habitatInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHabitatInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *habitatInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&habitat_v1beta1.Habitat{}, f.defaultInformer)
}

func (f *habitatInformer) Lister() v1beta1.HabitatLister {
	return v1beta1.NewHabitatLister(f.Informer().GetIndexer())
}
