apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: example-env-vars-habitat
  labels:
    source: operator-example
    app: env-vars-habitat
customVersion: v1beta2
spec:
  v1beta2:
    # the core/redis habitat service packaged as a Docker image
    image: habitat/redis-hab
    count: 1
    env:
      - name: HAB_REDIS
        value: '{ "port": "6999" }'
    service:
      name: redis
      topology: standalone
      # if not present, defaults to "default"
      group: foobar
